# 创建数据库的 Docker Compose 配置
version: '3.8'
services:
  postgres:
    image: postgres:15.15-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root@202601
      POSTGRES_DB: postgres